export const fakeData = [
  {
    id: 1,
    name: "Seemanto 1",
    age: 25,
    gender: "male",
    diagnosis: "covid",
    medications: "napa",
    prescriptionDate: "10-01-2022",
    nextVisitDate: "15-01-2022",
  },
  {
    id: 2,
    name: "Seemanto 2",
    age: 26,
    gender: "male",
    diagnosis: "covid",
    medications: "napa",
    prescriptionDate: "11-01-2022",
    nextVisitDate: "15-01-2022",
  },
  {
    id: 3,
    name: "Seemanto 3",
    age: 27,
    gender: "male",
    diagnosis: "covid",
    medications: "napa",
    prescriptionDate: "12-01-2022",
    nextVisitDate: "15-01-2022",
  },
  {
    id: 4,
    name: "Seemanto 4",
    age: 28,
    gender: "male",
    diagnosis: "covid",
    medications: "napa",
    prescriptionDate: "13-01-2022",
    nextVisitDate: "15-01-2022",
  },
  {
    id: 5,
    name: "Seemanto 5",
    age: 29,
    gender: "male",
    diagnosis: "covid",
    medications: "napa",
    prescriptionDate: "14-01-2022",
    nextVisitDate: "15-01-2022",
  },
];
